Repository xction-dev/xflix, pull requests merged in 2023-08, with the labels that each got.

#11 #10/feat/add mock data
  src/mock/contents.json
  src/mock/curations.json
Labels: enhancement, frontend

#18 Hotfix/pr and issue template
  .github/ISSUE_TEMPLATE/announcement.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: fix

#16 #13/feat/add login and dashboard
  src/app/dashboard/page.js
  src/app/globals.css
  src/app/login/page.js
  src/app/page.js
  src/app/page.module.css
  src/components/Curations/Carousel/Carousel.css
  src/components/Curations/Carousel/Carousel.js
  src/components/Curations/ContentCard/ContentCard.css
  src/components/Curations/ContentCard/ContentCard.js
  src/components/Curations/DashboardContainer/DashboardContainer.css
  src/components/Curations/DashboardContainer/DashboardContainer.js
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/Login/IDInput/IDInput.css
  src/components/Login/IDInput/IDInput.js
  src/components/Login/LoginContainer/LoginContainer.css
  src/components/Login/LoginContainer/LoginContainer.js
  src/components/Login/PWInput/PWInput.css
  src/components/Login/PWInput/PWInput.js
  src/components/SubmitButton/SubmitButton.css
  src/components/SubmitButton/SubmitButton.js
  src/mock/contents.json
  src/mock/curations.json
  src/utils/isPlayable.js
Labels: enhancement, frontend

#20 #19/feat/initiate server
  docs/api.md
  package.json
  src/app/api/contents/[content_id]/route.js
  src/app/api/contents/route.js
  src/app/api/curations/route.js
  src/app/api/ping/route.js
  src/utility/db.js
  yarn.lock
Labels: enhancement, backend

#27 refact: Change utility directory name
  src/app/api/contents/[content_id]/route.js
  src/app/api/contents/route.js
  src/app/api/curations/route.js
  src/components/Curations/ContentCard/ContentCard.js
  src/utils-client/isPlayable.js
  src/utils-server/db.js
Labels: fix

#28 feat: Add prettierrc
  .prettierrc
Labels: fix

#23 #21/feat/connect dashboard api
  src/app/dashboard/page.js
  src/app/globals.css
  src/app/login/page.js
  src/app/page.js
  src/components/Curations/Carousel/Carousel.css
  src/components/Curations/Carousel/Carousel.js
  src/components/Curations/ContentCard/ContentCard.css
  src/components/Curations/ContentCard/ContentCard.js
  src/components/Curations/DashboardContainer/DashboardContainer.css
  src/components/Curations/DashboardContainer/DashboardContainer.js
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/Login/IDInput/IDInput.css
  src/components/Login/IDInput/IDInput.js
  src/components/Login/LoginContainer/LoginContainer.css
  src/components/Login/LoginContainer/LoginContainer.js
  src/components/Login/PWInput/PWInput.css
  src/components/Login/PWInput/PWInput.js
  src/components/SubmitButton/SubmitButton.css
  src/components/SubmitButton/SubmitButton.js
  src/utils-client/isPlayable.js
Labels: enhancement, frontend

#30 #29/feat/login and register api
  docs/api.md
  docs/error.md
  src/app/api/contents/[content_id]/route.js
  src/app/api/contents/route.js
  src/app/api/curations/route.js
  src/app/api/echo/route.js
  src/app/api/ping/route.js
  src/app/api/users/login/route.js
  src/app/api/users/register/route.js
  src/components/Curations/DashboardContainer/DashboardContainer.js
  src/utils-server/db.js
  src/utils-server/validate.js
Labels: enhancement, backend
